### PR TITLE
Generalize and clarify the abstract to give a better understanding of the relationship of this document to other work.

### PR DESCRIPTION
**Pull request by jasonjgw**
This is a proposal to clarify the abstract (for consideration by the Maturity Model subgroup).

### CODE REVIEW

**Comment by maryjom** [comment]
@jasonjgw I don't know why, but the build for this change is failing.

**Comment by jasonjgw** [comment]
The HTML validity fixes hadn't been merged into this branch. I have attempted to fix this, and it should now be possible to merge it into main.

**Comment by jasonjgw** [comment]
I hope the automatic building and deployment script will run without error if this is merged into main together with #82.

**Comment by maryjom** [comment]
@jasonjgw I can merge, but may need help backing out if it causes the build to fail.

**Comment by jasonjgw** [comment]
I can offer to take care of it if there's a problem.

**Pull request merged**
