### PR TITLE
3-3-3-outcomes edit

### PR DESCRIPTION
**Pull request by jeffkline**
changed description of this support line item

### CODE REVIEW

**Comment by clapierre** [comment]
Jeff, you added a couple new files, an apple .DS_Store and an index.rtf
Can you delete those from your pull request?

**Comment by jeffkline** [comment]
Will try


Regards,


[A picture containing text, black, clock  Description automatically generated]<http://strategicaccessibility.com/>
    ***@***.***
    5  1  2  .  4  2  6  .  9   7  7  9

From: Charles LaPierre ***@***.***>
Date: Thursday, December 14, 2023 at 11:51 AM
To: w3c/maturity-model ***@***.***>
Cc: Jeff Kline ***@***.***>, Author ***@***.***>
Subject: Re: [w3c/maturity-model] 3-3-3-outcomes edit (PR #201)

Jeff, you added a couple new files, an apple .DS_Store and an index.rtf
Can you delete those from your pull request?

**Comment by jeffkline** [comment]
I got rid of the rtf I think , but it won’t let me delete the .ds file ☹

Regards,


[A picture containing text, black, clock  Description automatically generated]<http://strategicaccessibility.com/>
    ***@***.***
    5  1  2  .  4  2  6  .  9   7  7  9

From: Charles LaPierre ***@***.***>
Date: Thursday, December 14, 2023 at 11:51 AM
To: w3c/maturity-model ***@***.***>
Cc: Jeff Kline ***@***.***>, Author ***@***.***>
Subject: Re: [w3c/maturity-model] 3-3-3-outcomes edit (PR #201)

Jeff, you added a couple new files, an apple .DS_Store and an index.rtf
Can you delete those from your pull request?

**Comment by clapierre** [comment]
No problem we can try to add it later to the .ignore file.

Thanks
Charles
EOM

**Review by clapierre — APPROVED** [review]
This looks correct now, and changes were made.

**Comment by clapierre** [comment]
Waiting for your review / merge David. Nice work Jeff!

**Comment by Helixopp** [comment]
@clapierre Looks like Branch Conflicts need resolving first?

**Review by Helixopp — APPROVED** [review]
Good work, team.

**Comment by clapierre** [comment]
Sorry Jeff, for some reason the index.html file was renamed to 3-3-3-outcomes.html which was causing a conflict.
I have fixed this now. All checks passed and we should be able to Merge David.

**Comment by jeffkline** [comment]
Charles,

Thank you!!! Much appreciated!!!

Regards,


[A picture containing text, black, clock  Description automatically generated]<http://strategicaccessibility.com/>
    ***@***.***
    5  1  2  .  4  2  6  .  9   7  7  9

From: Charles LaPierre ***@***.***>
Date: Thursday, December 14, 2023 at 12:51 PM
To: w3c/maturity-model ***@***.***>
Cc: Jeff Kline ***@***.***>, Author ***@***.***>
Subject: Re: [w3c/maturity-model] 3-3-3-outcomes edit (PR #201)

Sorry Jeff, for some reason the index.html file was renamed to 3-3-3-outcomes.html which was causing a conflict.
I have fixed this now. All checks passed and we should be able to Merge David.

**Pull request merged**
